import Foundation

let socialMedia = "Social Media has skyrocketed over the past decade. There has been a growth spurt in the number of users of Facebook, Twitter, Instagram and Snapchat and other social media platforms and the amount of time spent on them has been colossal and of great discussion. The news shared on Social Media spreads rapidly and covers a lot of ground. We can use this to our advantage in spreading awareness about Breast cancer to a wide range of demographics. Using different platforms, we can cover more ground and spread the information about Breast Cancer and can even interact with many individuals for the same. We can respond to certain queries raised by the public and help them understand the need of this awareness."

let onlineStreaming = "Innovation and Technology have become an inseparable element of the modern-day healthcare system and it is difficult to think of any healthcare services without making a noteworthy reference to technology. \n As more people are compelled to stay at home to try to curb the spread of the novel coronavirus, the concept of a bored, cable-cutting consumer searching for things to constantly watch for weeks on end has become a reality. Streaming services, from premium ones like Netflix to free platforms like YouTube and Instagram, gained an enormous number of viewers during the lockdown. \n YouTube reported that since March 15, there was a 590% increase of average global daily uploads. Every influencer has a plethora of followers on these social media platforms, therefore if they discuss about the mythological questions that are prevalent in the society or use a pink background during their live sessions showing their support towards this cause, it would help us in reaching out to all the colours in the population because social media channels push live streams to the top of users’ feeds and notify more often about live streams than any other activity thereby, this would ensure brimming success of this campaign."

let onlineClasses = "The pandemic has had far-reaching consequences and times like these make us realize that the world will never stop moving and that we are supposed to adapt accordingly and move with the time. Online classes being the most prominent example. \n We can use this as an opportunity by urging the faculties to impart basic Breast cancer information to students because the younger generation is going to be the face of our future. \n Educational institutions can also introduce a new non-evaluative subject to imbibe basic knowledge about Breast cancer. They can make these classes more interesting and more interactive by inviting specialized doctors to their classes or several patients to discuss the issue with students and answer their queries. The faculties can also invite parents for such classes and spread information about Breast cancer with them. This can prove to be an extremely informative session for the students as well as for parents."

let printMedia = "Print media still remains one of the most conventional forms of creating awareness amongst the masses. With India at the cusp of the digital revolution, print media still holds an edge over electronic media. \n India has a massive population of 130 million people with every individual having access to the newspaper. Our country is the second-largest producer of newspaper and there are around 1,00,000 registered newspapers and 300 different magazines in over 15 categories all over the nation. There are more than 22 languages in which the newspaper is published and distributed to every possible corner of the country. \n Newspaper and magazines have a wide range of network which can help escalate the awareness program. The print media will play a praiseworthy role in disseminating information to every nook and cranny of the country. Newspapers play a key role in spreading any news, notification, or any other piece of important information to a large group of people in a very short period of time. A couple of things such as a pink page specially dedicated to Breast cancer education would do the needful. Informing people where the country stands and what all steps have been taken for the proper treatment in every part of the country would play a vital role in creating awareness."
